function [XDEN,wptDEN] = func_denoise_wp2d(X)
% FUNC_DENOISE_WP2D Saved Denoising Process.
%   X: matrix of data
%   -----------------
%   XDEN: matrix of denoised data
%   wptDEN: wavelet packet decomposition (wptree object)

%  Auto-generated by Wavelet Toolbox on 01-Nov-2023 11:31:05

% Analysis parameters.
%---------------------
Wav_Nam = 'db3';
Lev_Anal = 3;
Ent_Nam = 'shannon';
Ent_Par = 0;

% Denoising parameters.
%-----------------------
% meth = 'sqtwologuwn';
sorh = 's';    % Specified soft or hard thresholding
thrSettings = {sorh,'nobest',4.852258868382912,1};
roundFLAG = true;

% Decompose using WPDEC2.
%-----------------------
wpt = wpdec2(X,Lev_Anal,Wav_Nam,Ent_Nam,Ent_Par);

% Nodes to merge.
%-----------------
n2m = [];
for j = 1:length(n2m)
    wpt = wpjoin(wpt,n2m(j));
end

% Denoise using WPDENCMP.
%------------------------
[XDEN,wptDEN] = wpdencmp(wpt,thrSettings{:});
if roundFLAG , XDEN = round(XDEN); end
if isequal(class(X),'uint8') , XDEN = uint8(XDEN); end
